const intl = {
    en: {
        "hello": 'Hello',
        "signIn": 'Sign In',
        "rewards": 'Rewards',
        "orders": 'Orders',
        "cart": 'Cart',
        "your": 'Your',
        "prime": 'Prime',
        "product_23445930": "Amazon Echo (3rd generation) | Smart speaker with Alexa, Charcoal Fabric",
        "product_12321341": "The Lean Startup: How Constant Innovation Creates Radically Successful Business Paperback",
        "product_49538094": "Kenwood kMix Stand Mixer for Baking, Stylish Kitchen Mixer with K-beater, Dough Hook and Whisk, 5 Litre Glass Bowl",
        "product_4903850": "Samsung LC49RG90SSUXEN 49' Curved LED Gaming Monitor",
        "product_3254354345": "New Apple iPad Pro (12.9-inch, Wi-Fi, 128GB) - Silver (4th Generation)",
        "product_90829332": "Samsung LC49RG90SSUXEN 49' Curved LED Gaming Monitor -  Super Ultra Wide Dual WQHD 5120 x1440",
        "checkout": "Your Shopping Basket",
        "proceed_pay": "Proceed to Checkout",
        "gift": "This order conatins a gift",
        "subtotal": "SubTotal",
        "item": "items",
        "Quick_Look": "Quick Look",
        "Deals": "Top Trending Deals",
        "Your_Orders": "Your Orders",
        "checkout_thing": "Checkout",
        "address": "Delivery Address",
        "Delivery": "Review items and Delivery",
        "Payment_Method": "Payment Method",
        "Order_Total": "Order Total",
        "Processing": "Processing",
        "Buy_Now": "Buy Now"
    },
    hin: {
        "hello": 'हैलो',
        "signIn": 'साइन इन करें',
        "rewards": 'पुरस्कार',
        "orders": 'और ऑर्डर',
        "cart": 'कॉर्ट',
        "your": 'आपका',
        "prime": 'Prime',
        "product_23445930": 'अमेज़न इको (तीसरी पीढ़ी) | एलेक्सा, चारकोल फैब्रिक के साथ स्मार्ट स्पीकर',
        "product_12321341": "द लीन स्टार्टअप: हाउ कॉन्स्टेंट इनोवेशन रेडिकली सक्सेसफुल बिजनेस पेपरबैक बनाता है",
        "product_49538094": "बेकिंग के लिए केनवुड केमिक्स स्टैंड मिक्सर, के-बीटर, आटा हुक और व्हिस्क के साथ स्टाइलिश किचन मिक्सर, 5 लीटर ग्लास बाउल",
        "product_4903850": "सैमसंग LC49RG90SSUXEN 49 'घुमावदार एलईडी गेमिंग मॉनिटर",
        "product_3254354345": "नया Apple iPad Pro (12.9 इंच, वाई-फाई, 128 जीबी) - सिल्वर (4th जनरेशन)",
        "product_90829332": "सैमसंग LC49RG90SSUXEN 49 'कर्व्ड एलईडी गेमिंग मॉनिटर - सुपर अल्ट्रा वाइड ड्यूल WQHD 5120 x1440",
        "checkout": "आपका चेकआउट बास्केट",
        "gift": "यह आदेश एक उपहार को जीतता है",
        "subtotal": "सबटोटल",
        "item": "आइटम",
        "proceed_pay": "चुकाने के लिए आगे बढ़ना शुरू करो",
        "Quick_Look": "त्वरित देखो",
        "Deals": "टॉप ट्रेंडिंग डील्स",
        "Your_Orders": "तुम्हारे ऑर्डर",
        "checkout_thing": "चेक आउट",
        "address": "डिलिवरी का पता",
        "Delivery": "वस्तुओं और वितरण की समीक्षा करें",
        "Payment_Method": "भुगतान का तरीका",
        "Order_Total": "कुल आदेश",
        "Processing": "प्रसंस्करण",
        "Buy_Now": "अभी खरीदें"


    },
    urdu: {}
}

export { intl };